---
abstract: 'Interface to the Northern 911 ALI database'
author:
  - 'Mark Wells <mark@freeside.biz>'
build_requires:
  File::ShareDir::Install: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Northern911
no_index:
  directory:
    - t
    - inc
requires:
  DateTime: 0
  File::ShareDir: 0
  XML::Compile: 1
  XML::Compile::SOAP: 3
  XML::Compile::WSDL11: 3
  perl: 5.006
version: 0.1
